spring:
  application:
    api-prefix: /api/v1
    name: spring-boot-rest-api
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
server:
  port: 8080

payment:
  vnPay:
    url: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
    tmnCode: 58X4B4HP
    secretKey: 6YXQZQJ
    returnUrl: http://localhost:8080/api/v1/payment/vnpay-return
    version: 2.1.0
    command: pay
    orderType: other

